### ISSUE TITLE
Awesome report viewer, couple of issues

### ISSUE THREAD

**Issue by beckerben** [alanjuden/MvcReportViewer#25]
You have a great start here to a pretty slick utility to bridge the missing gap that exists currently with SSRS and aspnet core.  I got this working and noticed a few things I'll have to dig into:

1) Exporting to any format produces an error.  I have the stack dump below.

2) For reports with a boolean parameter, I cannot get the report to render when the checkbox is "unchecked", it must be checked or a get an error.

3) It would be great to add the jquery date selector for parameters that are "datetime".  

Here's the output of the error when choosing to export:

```
An unhandled exception occurred while processing the request.

FaultException: An attempt was made to set a report parameter 'format' that is not defined in this report. ---> Microsoft.ReportingServices.Diagnostics.Utilities.UnknownReportParameterException: An attempt was made to set a report parameter 'format' that is not defined in this report.
System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)

AggregateException: One or more errors occurred. (An attempt was made to set a report parameter 'format' that is not defined in this report. ---> Microsoft.ReportingServices.Diagnostics.Utilities.UnknownReportParameterException: An attempt was made to set a report parameter 'format' that is not defined in this report.)
System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)

Stack Query Cookies Headers
FaultException: An attempt was made to set a report parameter 'format' that is not defined in this report. ---> Microsoft.ReportingServices.Diagnostics.Utilities.UnknownReportParameterException: An attempt was made to set a report parameter 'format' that is not defined in this report.
System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
System.Threading.Tasks.Task.GetResultCore(bool waitCompletionNotification)
AlanJuden.MvcReportViewer.ReportServiceHelpers.GetReportParameters(ReportViewerModel model, bool forRendering) in ReportServiceHelpers.cs
			var parameters = service.GetReportParametersAsync(model.ReportPath, historyID, forRendering, values, rsCredentials).Result;
AlanJuden.MvcReportViewer.ReportServiceHelpers.ExportReportToFormat(ReportViewerModel model, string format, Nullable<int> startPage, Nullable<int> endPage) in ReportServiceHelpers.cs
			var definedReportParameters = GetReportParameters(model, true);
AlanJuden.MvcReportViewer.ReportController.ExportReport(string reportPath, string format) in ReportController.cs
			var contentData = ReportServiceHelpers.ExportReportToFormat(model, format);
lambda_method(Closure , object , Object[] )
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionFilterAsync>d__28.MoveNext()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeAsync>d__18.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.VisualStudio.Web.BrowserLink.BrowserLinkMiddleware+<ExecuteWithFilter>d__7.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__6.MoveNext()

Show raw exception details
System.ServiceModel.FaultException: An attempt was made to set a report parameter 'format' that is not defined in this report. ---> Microsoft.ReportingServices.Diagnostics.Utilities.UnknownReportParameterException: An attempt was made to set a report parameter 'format' that is not defined in this report.
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
AggregateException: One or more errors occurred. (An attempt was made to set a report parameter 'format' that is not defined in this report. ---> Microsoft.ReportingServices.Diagnostics.Utilities.UnknownReportParameterException: An attempt was made to set a report parameter 'format' that is not defined in this report.)
System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
System.Threading.Tasks.Task.GetResultCore(bool waitCompletionNotification)
AlanJuden.MvcReportViewer.ReportServiceHelpers.GetReportParameters(ReportViewerModel model, bool forRendering) in ReportServiceHelpers.cs
			var parameters = service.GetReportParametersAsync(model.ReportPath, historyID, forRendering, values, rsCredentials).Result;
AlanJuden.MvcReportViewer.ReportServiceHelpers.ExportReportToFormat(ReportViewerModel model, string format, Nullable<int> startPage, Nullable<int> endPage) in ReportServiceHelpers.cs
			var definedReportParameters = GetReportParameters(model, true);
AlanJuden.MvcReportViewer.ReportController.ExportReport(string reportPath, string format) in ReportController.cs
			var contentData = ReportServiceHelpers.ExportReportToFormat(model, format);
lambda_method(Closure , object , Object[] )
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionFilterAsync>d__28.MoveNext()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeAsync>d__18.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.VisualStudio.Web.BrowserLink.BrowserLinkMiddleware+<ExecuteWithFilter>d__7.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__6.MoveNext()

Show raw exception details
```

**Comment by alanjuden** [comment]
@beckerben, was this with my most recent release 1.0.0.8 that you had the export issue and the inability to leave a checkbox blank?

**Comment by beckerben** [comment]
@alanjuden, yes, I downloaded it earlier this evening and was testing it out.  I was experimenting with the core version only.  I did not do the same testing with the non core one.

**Comment by alanjuden** [comment]
@beckerben, I've just pushed a new build that corrects your first two issues. I'm going to add a new feature request for the third suggestion.

**Comment by beckerben** [comment]
@alanjuden awesome! I will checkout the latest build and let you know how it goes!

**Comment by beckerben** [comment]
@alanjuden, confirmed 1 & 2 fixed, I look forward to point 3!
